# ~/.config/sheldon/plugins.toml

shell = "zsh"

[plugins]

[plugins.powerlevel10k]
git = "https://github.com/romkatv/powerlevel10k"

[plugins.zsh-autosuggestions]
git = "https://github.com/zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
git = "https://github.com/zsh-users/zsh-syntax-highlighting"

[plugins.zsh-vi-mode]
git = "https://github.com/jeffreytse/zsh-vi-mode"

[plugins.fzf]
git = "https://github.com/junegunn/fzf"

[plugins.zoxide]
git = "https://github.com/ajeetdsouza/zoxide"

[plugins.ssh-agent] # remember ssh key passphrase for session
github = "ohmyzsh/ohmyzsh"
dir = "plugins/ssh-agent"
